language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t singhpa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true singhpa/docker-react npm run test